version: '2.4'
#
#FOR DEVELOPMENT PURPOSE ONLY!!!!!!
#
#
services:

    app:
      image: localhost:5000/prusa_app
      working_dir: /home/docker/src
      environment:
        - DATABASE_URI=postgresql+psycopg2://postgres:${DB_PASSWORD}@db:5432/${DB_NAME}
      ports:
        - "8004:5000"

    db:
      image: library/postgres:12.5-alpine
      restart: always
      environment: [ "POSTGRES_USER=postgres","POSTGRES_PASSWORD=${DB_PASSWORD}","POSTGRES_DB=${DB_NAME}" ]
      volumes: [ "db_data:/var/lib/postgresql/data" ]
      ports:
        - "65432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 30s
        timeout: 30s
        retries: 3

    registry:
      image: registry:2
      restart: always
      ports:
        - "5000:5000"


volumes:
  db_data:
